blank_issues_enabled: false
contact_links:
  - name: Discord (real-time help)
    url: https://discord.gg/UPpVShYDaf
    about: For quick questions, or if you're not sure whether something is even a bug.
